### ISSUE TITLE
How to avoid showing error?

### ISSUE THREAD

**Issue by hmaesta** [dword-design/vue-mermaid-string#31]
When an invalid string is attached to `vue-mermaid-string` it _literally_ returns a bomb:
![Screen Shot 2021-08-05 at 20 20 00](https://user-images.githubusercontent.com/741969/128433455-3acfc716-fbde-41ee-9aef-9e0f0d71f660.png)

How can I avoid this behavior and show my own warning?

[Demo sandbox](https://codesandbox.io/s/determined-pine-6khb2?file=/components/Tutorial.vue) - click on the button until you get an error.

**Comment by dword-design** [comment]
@hmaesta Hey, yeah good point. I've added a PR that adds custom error handling. You can test it by checking out the project, running `yarn && yarn prepublishOnly` and adding it to your project. I've also documented it in the README.
