### ISSUE TITLE
Node click event

### ISSUE THREAD

**Issue by jfanals** [dword-design/vue-mermaid-string#34]
Hi Sebastian, congratulations on your plugin, it works like a charm, super easy to install and setup.

Are you planning on implementing a node click event?

Thanks

**Comment by dword-design** [comment]
@jfanals Good idea. Shouldn't be too big of a deal since Mermaid supports it. Only thing is that Mermaid does not seem to render clickable nodes as buttons. I've written an [issue](https://github.com/mermaid-js/mermaid/issues/2278) for that.

**Comment by jfanals** [comment]
Thank you for looking into this.

There is another flowchart vue mermaid implementation that does allow clicks on nodes, I guess they took an alternative approach:
https://github.com/robin1liu/vue-mermaid

BTW. I really like your take of rendering the diagram via a simple string :)

**Comment by dword-design** [comment]
@jfanals I'm currently looking closer into this. The main problem here is that in Mermaid, you register click events by adding `click <nodeId> <callBackName>` to the diagram for each clickable node. `vue-mermaid` implicitly generates these clauses. When passing the diagram as a string, the question arises if you still want to declare the click events like this or if they should completely be handled by the component. What's your opinion on this?

**Comment by jfanals** [comment]
My use case: we have a quiz that is composed of questions, we have natural (linear) flow from one question to the next, but you can also build logic to jump several questions...

For the interface we have on the left side of the screen the different question in a column, and on the right the flowchart working as a preview of the logic that is being built.

Ideally when clicking a node on the flowchart a method inside the component, where the flowchart is rendered, can be triggered. It would only need to pass the nodeId in order for me to be able to scroll to the correct question.

I hope this helps clarify the situation.

**Comment by dword-design** [comment]
@jfanals Alright I linked a PR that implements click events. From the approach it's pretty close to the official Mermaid.js approach except that the callback is injected into the diagram. To test, check out the branch, build it via `yarn prepublishOnly` and add it to your project via `yarn add ../vue-mermaid-string`. Then add the click events via `click <nodeId>` to your diagram string.

**Comment by jfanals** [comment]
Hi @dword-design, sorry for the delayed the response.

I just tried installing your component from that particular branch. I could not run the `yarn prepublishOnly` command, I could add it with `yarn add ../vue-mermaid-string`... but I am now unable to import it inside my component :(

I have also tried installing the branch via
`yarn add https://github.com/dword-design/vue-mermaid-string#c3c545dc607c90fdf3f937696d1da457476ec55d`
but no success.

Could you please give me more tips on how to import it?

**Comment by dword-design** [comment]
@jfanals Sure no problem. Did you run `yarn --frozen-lockfile` before to install the dependencies? What's the error message? It needs to succeed, otherwise the files to import are not generated.

**Comment by jfanals** [comment]
I think the issue might be because I have the yarn version 1.22.11 (installed via brew). What version are you using?

**Comment by dword-design** [comment]
@jfanals `1.22.4`. So should be fine.

**Comment by jfanals** [comment]
When I try to run `yarn prepublishOnly` I get the following error:
`error Command "prepublishOnly" not found.`

You think the PR could break the current functionality? What about adding it to master directly?

**Comment by dword-design** [comment]
@jfanals Are you sure you checked out the correct branch (`dword-design/node-click-event-34`) and `cd`ed into the directory? Otherwise check `package.json` and see if `prepublishOnly` is there under `scripts`.

It probably doesn't break current functionality, but it's always better to test and review on a PR.

**Comment by jfanals** [comment]
When I try running `yarn prepublishOnly` on the `../vue-mermaid-string` directory with the branch `dword-design/node-click-event-34`

I get the following error
```
% yarn prepublishOnly
yarn run v1.22.11
$ base prepublishOnly
/bin/sh: base: command not found
```

It does look like I can run the `prepublishOnly` command there, but I am missing `base`...

**Comment by dword-design** [comment]
@jfanals I sent you an email. I think it's easier :).

**Comment by shaneblaser** [comment]
Can we merge this feature into the main branch?

**Comment by dword-design** [comment]
@jfanals Sorry for the big delay. Was very busy and I had to make some adjustments to the build process to make this one work. Tested it again and now it should work. I merged the PR.
