### ISSUE TITLE
click event failure

### ISSUE THREAD

**Issue by rjansen2573** [dword-design/vue-mermaid-string#58]
This works like documented:
graph TD
              A --> B
              click A
              click B
But this does not:
graph TD
              A --> BB
              click A
              click BB
if I use id's longer than one character it crashes mermaid version 8.13.6

**Comment by rjansen2573** [comment]
regex:
        /^(\s*click\s+[^\s]\s*)$/gm,
is missing a '+'
should be:
        /^(\s*click\s+[^\s]       +      \s*)$/gm,

**Comment by dword-design** [comment]
@rjansen2573 Thanks for reporting! It's fixed.
