### ISSUE TITLE
dynamic diagram change

### ISSUE THREAD

**Issue by ninjawule** [dword-design/vue-mermaid-string#59]
Hi! 

First, thank you very much for this great component!

I'm using it to display graph structures existing on a server. 

These graphs can evolve in realtime, and so, by polling them from inside a Vue app, I want to be able to refresh the Mermaid diagrams displayed by this app. 

But even though the `value` property of the `vue-mermaid-string` component is updated, the diagrams are not refreshed.

Would you have some tip about how to deal with such a use case?

Thank you again

**Comment by rjansen2573** [comment]
Had the same issue.
My vue-mermaid-string is inside another component because i wanted to manipulate the value before it goes into mermaid and decode the click events afterwards.
I placed a :key="..." on the outside component and now the mermaid does update when the key changes.

**Comment by ninjawule** [comment]
Hi rjansen2573 , thank you ! I've also figured this out, using a key. The inconvenient with a re-rendering though, is that the view gets scrolled back somehow, which prevent seeing in real time the changes at the bottom of a long diagram; but I guess this has to do with Vue mechanics, not this component.

**Comment by dword-design** [comment]
@ninjawule @rjansen2573 Thanks for reporting, it's fixed!

**Comment by ninjawule** [comment]
Hi @dword-design, I've looked at your last commit. Does it mean we won't have to use tricks like using a `:key` on the component ?

**Comment by dword-design** [comment]
@ninjawule That's right
